name: auto-tag
on:
  push:
    branches:
    - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: tag
      run: |
        git config user.name "sif741852014"
        git config user.email "asiftkmohammed@gmail.com"
    - name: push
      env:
        GITHUB_TOKEN: ${{ secrets.pat }}
      run: |
        echo $GITHUB_TOKEN
        TAG_NAME="build-$(date +'%Y%m%d%H%M%S')"
        echo $TAG_NAME
        git tag $TAG_NAME
        echo "Pushing tag $TAG_NAME"
        git push https://x-access-token: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@github.com/asif741852014/settingdockeraction.git $TAG_NAME || (echo "Push failed with exit code $?"; exit 1)
