name: auto-tag
on:
  push:
    branches:
    - main
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: tag
      run: |
        git config user.name "asif741852014"
        git config user.email "asiftkmohammed@gmail.com"
    - name: push
      env:
        GITHUB_TOKEN: ${{ secrets.SSS }}
      run: |
        echo $GITHUB_TOKEN
        TAG_NAME="build-$(date +'%Y%m%d%H%M%S')"
        echo $TAG_NAME
        git tag $TAG_NAME
        echo "Pushing tag $TAG_NAME"
        git push origin $TAG_NAME
        
