name: hai
on:
    push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: run action
          uses: ./